### ISSUE TITLE
Ability to add custom classNames

### ISSUE THREAD

**Issue by abelmark** [cameronbourke/react-hamburger-menu#14]
I did this locally.  I can create a PR if you'd like.

**Comment by liliakai** [comment]
Would be handy for custom styling, hover effects, etc...

**Comment by smerth** [comment]
I am not sure if this is the same issue but I cannot use this excellent component with styled-components because the className prop is not being passed into the component.  That's a requirement of styled-components.

I think the solution is

@ HamburgerMenu.js

    ...
      return _react.default.createElement("div", {
        style: styles.container,
        onClick: props.menuClicked,
        className: props.className
      }, _react.default.createElement("span", {
        style: Object.assign({}, styles.lineBase, styles.firstLine)
      }), _react.default.createElement("span", {
        style: Object.assign({}, styles.lineBase, styles.secondLine)
      }), _react.default.createElement("span", {
        style: Object.assign({}, styles.lineBase, styles.thirdLine)
      }));
    }
    ...

Line 5 passes in the className prop.

That means you can style the component using styled-components and emotion.

**Comment by cameronbourke** [comment]
@smerth I appreciate the kind words about the library! Unfortunately I'm not actively maintaining this repo but I've merged your PR, so we can close this thanks to #18. I'll try and have a new release out the door tomorrow for you.
